# Generated by Django 2.1.5 on 2019-03-01 02:09

from django.db import migrations


def load_times(apps, schema_editor):
    Time = apps.get_model('scheduler', 'TimeSlot')
    for day in range(7):
        for hour in range(24):
            time = Time(dayOfWeek=day, hour=hour)
            time.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_times),
    ]
